### ISSUE TITLE
Tracing integration 

### ISSUE THREAD

**Issue by nikolay-te** [sunng87/metriki#81]
I might be doing something wrong, but I can't get the MetrikiLayer to work with tracing.

This code:
```
use metriki_core::global::global_registry;
use metriki_tracing::MetrikiLayer;
use tracing_subscriber::prelude::*;

fn main() {
    let metriki = MetrikiLayer::new(global_registry());
    tracing_subscriber::registry().with(metriki).init();
}
```

Produces errors:
```
error[E0277]: the trait bound `MetrikiLayer: __tracing_subscriber_Layer<Registry>` is not satisfied
    --> src/main.rs:7:41
     |
7    |     tracing_subscriber::registry().with(metriki).init();
     |                                    ---- ^^^^^^^ the trait `__tracing_subscriber_Layer<Registry>` is not implemented for `MetrikiLayer`
     |                                    |
     |                                    required by a bound introduced by this call
     |
note: required by a bound in `with`
    --> /Users/ndenev/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.11/src/layer/mod.rs:1392:12
     |
1392 |         L: Layer<Self>,
     |            ^^^^^^^^^^^ required by this bound in `with`

error[E0599]: the method `init` exists for struct `Layered<MetrikiLayer, Registry>`, but its trait bounds were not satisfied
  --> src/main.rs:7:50
   |
7  |     tracing_subscriber::registry().with(metriki).init();
   |                                                  ^^^^ method cannot be called on `Layered<MetrikiLayer, Registry>` due to unsatisfied trait bounds
   |
  ::: /Users/ndenev/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.11/src/layer/layered.rs:23:1
   |
23 | pub struct Layered<L, I, S = I> {
   | -------------------------------
   | |
   | doesn't satisfy `Layered<MetrikiLayer, Registry>: SubscriberInitExt`
   | doesn't satisfy `_: Into<tracing_core::dispatcher::Dispatch>`
   |
   = note: the following trait bounds were not satisfied:
           `Layered<MetrikiLayer, Registry>: Into<tracing_core::dispatcher::Dispatch>`
           which is required by `Layered<MetrikiLayer, Registry>: SubscriberInitExt`
           `&Layered<MetrikiLayer, Registry>: Into<tracing_core::dispatcher::Dispatch>`
           which is required by `&Layered<MetrikiLayer, Registry>: SubscriberInitExt`
           `&mut Layered<MetrikiLayer, Registry>: Into<tracing_core::dispatcher::Dispatch>`
           which is required by `&mut Layered<MetrikiLayer, Registry>: SubscriberInitExt`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `metriki-test` due to 2 previous errors
```

These are the crates I'm using in this test:
```
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = [
    "env-filter",
    "json",
    "registry",
] }
metriki-core = "1.7.4"
metriki-prometheus-exporter = "0.1.1"
metriki-tracing = "0.1.0"
```

**Comment by sunng87** [comment]
This seems weird. Have you checked my example [here](https://github.com/sunng87/metriki/blob/master/metriki-tracing/examples/simple.rs) ? I can compile with the way you setup subscriber. I'm afraid there is version conflict. Do you have a repo to reproducing this?

**Comment by nikolay-te** [comment]
Yes, it does seem like a version conflict. I've tried again now with the example.rs code and I get the same.
Here is the full `Cargo.toml`:
```
[package]
name = "metriki-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = [
    "env-filter",
    "json",
    "registry",
] }
metriki-core = "1.7.4"
metriki-tracing = "0.1.0"
metriki-log-reporter = "0.1.4"
env_logger = "0.9.0"
```

`src/main.rs`:
```
use std::time::Duration;

use metriki_core::global::global_registry;
use metriki_log_reporter::LogReporterBuilder;
use metriki_tracing::MetrikiLayer;
use tracing::Level;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::registry::Registry;

fn main() {
    env_logger::init();
    LogReporterBuilder::default()
        .registry(global_registry())
        .interval_secs(2)
        .build()
        .unwrap()
        .start();

    let layer = MetrikiLayer::new(global_registry());
    let subscriber = Registry::default().with(layer);
    tracing::subscriber::set_global_default(subscriber).unwrap();

    loop {
        let span = tracing::span!(Level::INFO, "demo");
        let _enter = span.enter();

        tracing::info!("demo_sleep");
        std::thread::sleep(Duration::from_millis(1000));
    }
}
```

Running/building this gives:
```
error[E0277]: the trait bound `MetrikiLayer: __tracing_subscriber_Layer<Registry>` is not satisfied
    --> src/main.rs:20:47
     |
20   |     let subscriber = Registry::default().with(layer);
     |                                          ---- ^^^^^ the trait `__tracing_subscriber_Layer<Registry>` is not implemented for `MetrikiLayer`
     |                                          |
     |                                          required by a bound introduced by this call
     |
note: required by a bound in `with`
    --> /Users/ndenev/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.11/src/layer/mod.rs:1392:12
     |
1392 |         L: Layer<Self>,
     |            ^^^^^^^^^^^ required by this bound in `with`

error[E0277]: the trait bound `MetrikiLayer: __tracing_subscriber_Layer<Registry>` is not satisfied
  --> src/main.rs:21:45
   |
21 |     tracing::subscriber::set_global_default(subscriber).unwrap();
   |     --------------------------------------- ^^^^^^^^^^ the trait `__tracing_subscriber_Layer<Registry>` is not implemented for `MetrikiLayer`
   |     |
   |     required by a bound introduced by this call
   |
   = note: required because of the requirements on the impl of `tracing::Subscriber` for `Layered<MetrikiLayer, Registry>`
note: required by a bound in `tracing::subscriber::set_global_default`
  --> /Users/ndenev/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.35/src/subscriber.rs:41:8
   |
41 |     S: Subscriber + Send + Sync + 'static,
   |        ^^^^^^^^^^ required by this bound in `tracing::subscriber::set_global_default`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `metriki-test` due to 2 previous errors
```

**Comment by sunng87** [comment]
Thank you! I can reproduce this now. Let me see how to fix it.

**Comment by sunng87** [comment]
I just realized current released `metriki-tracing` depends on a `0.2` release of `tracing-subscriber`. So it has the conflict. `cargo tree -d` is a quick inspector for this kind of issue. I will create a new release soon work with `0.3` of `tracing-subscriber`.

**Comment by sunng87** [comment]
This should be fixed in `metriki-tracing = "0.2"`
